- Install-RustToolchain.ps1
- install-rust-toolchain.sh
Check the minimal version of installed rustc.
When the requirement does not match then invoke rustup to update the version.
Closes #11
> fix: check for minimal rustc version for bash

- .github/actions/build/build-rust-std/action.yaml
- .github/actions/build/build-rustc/action.yaml
- .github/actions/build/build-src/action.yaml
- .github/actions/build/build-tools/action.yaml
- .github/actions/tools/setup-libudev/action.yaml
- .github/actions/tools/setup-ninja/action.yaml
- .github/actions/tools/setup-python/action.yaml
- .github/actions/util/checkout-esp-rust/action.yaml
- .github/actions/util/create-archive/action.yaml
- .github/actions/util/read-artifacts/action.yaml
- .github/actions/util/setup-envs/action.yaml
- .github/actions/util/symlink-working-dir/action.yaml
- .github/actions/util/upload/action.yaml
- .github/workflows/build-rust-src-dispatch.yaml
- .github/workflows/build-rust-x86_64-apple-darwin-dispatch.yaml
- .github/workflows/build-rust-x86_64-pc-windows-msvc-dispatch.yaml
- .github/workflows/build-rust-x86_64-unknown-linux-gnu-dispatch.yaml
- .github/workflows/test-rust-x86_64-apple-darwin-dispatch.yaml
- .github/workflows/test-rust-x86_64-pc-windows-msvc-dispatch.yaml
- .github/workflows/test-rust-x86_64-unknown-linux-gnu-dispatch.yaml
Hi,
I've recently done a bit of a re-write of the github workflow scripts
From what I can gather I think they might be currently setup for self-hosted runners
This is the first time I've worked on github workflow so I don't expect this to go through as is, given it's size
more just some suggestions / ideas to get this running on github's native runners
Since I'd imagine a lot will depend on personal preference
Also I'm guessing the main branch is the one to push to
I've managed to add a few fixes / break things down into chunks here and there
So some of this may be of use.
So far the results of the builds I've done on the fork are viewable here
* https://github.com/Hecatron-Forks/rust-build/releases/tag/v1.56.0.1
* https://github.com/Hecatron-Forks/rust-build/actions
A lot of the main …
> Workflow changes for running on native github runners

- README.md
Podman is more agnostic than Docker in regard to the default container registry. As such, we should specify it to be docker.io explicitly.
> Fully qualify podman example

- install-rust-toolchain.sh
- support/rust-build/aarch64-unknown-linux-gnu/build.sh
- support/rust-build/rename-rust-release.sh
- support/rust-build/x86_64-unknown-linux-gnu/build.sh
- test-rust-toolchain.sh
Replace all occurrences of `#!/bin/bash` with `#!/usr/bin/env bash` in order to improve the [compatibility](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my).
Closes #39
> Update shell scripts' shebang to use env

- README.md
Hello,
I found the Docker/Podman section in the Readme a bit confusing. Here's an edit making it more apparent that there is a toolchain-only container available on Dockerhub.
BTW, the `rust-idf-examples` image hasn't been updated in a while (about a month). Not sure if that's intentional.
Thanks for your work!
Jens
> Add info to README about container images.

- README.md
Spilting the long `apt install` line into two physical lines.
The two short lines are still one logical line due the bashslash being _continueing line_ character.
> Less horizontal scrolling

- install-rust-toolchain.sh
The --clear-cache option requires an argument: YES or NO.
If shift is called only once, then the value of --clear-cache
is parsed as an argument in its own right.
This leads to either YES or NO being stored and then restored
as a positional argument. It doesn't currently seem to be harmful
but it is inaccurate and could lead to bugs in the future.
> Fix argument parsing bug for --clear-cache option

- install-rust-toolchain.sh
The 'install-rust-toolchain.sh' file contains a typo ('instalation') and a missing space in the script's output.
> Fix typos and punctuation in output of 'install-rust-toolchain.sh' file

- idf-rust.Containerfile
- install-rust-toolchain.sh
Add logic to allow installing [`wokwi-server`](https://github.com/MabezDev/wokwi-server/tree/master/src) and [`web-flash`](https://github.com/bjoernQ/esp-web-flash-server) from the installer.
> Add options to install wokwi-server and web-flash

- install-rust-toolchain.sh
- test-rust-toolchain.sh
- Deleted unused functions like `install_rust`
- Avoid installing Xtensa GCC
- Install only `nightly` toolchain for Xtensa targets, instead of `stable` and `nightly` as is sufficient
- LLVM Clang is now only installed for Xtensa targets
- Move the logic where we check if we need to install esp-idf
- Update test-rust-toolchain CI to allow different git repos
Closes #72
> Installer improvements

- install-rust-toolchain.sh
Since cargo-generate/cargo-generate/pull/620 got merged, from [release 0.15.2](https://github.com/cargo-generate/cargo-generate/releases/tag/v0.15.2) we can now use binary package for `aarch64-unknown-linux-gnu`
> Add cargo-generate url and bin file for `aarch64-unknown-linux-gnu`

- install-rust-toolchain.sh
I no longer see the value in having logic for `espmonitor` in the installer since we now have all of his features in `espflash` and we are not generating binaries for the latest releases of `espmonitor` we only have one binary uploaded to `rust-build release v1.60.0.1`
> Remove espmonitor

- .github/workflows/installer-check.yaml
As I am tired of breaking the installer, I figured out that this CI would be helpful, it compiles the `esp-idf-template` project for all boards and the 2 esp-idf versions: `master` and `release/v4.4` (`master` is failing due to https://github.com/esp-rs/esp-idf-sys/issues/99) and also builds `esp-template` for all boards.
The installer is way more complex than what we are testing here, but it's a start and later on, we could add more test cases.
> Add some CI to build template projects when changing the installer

- .github/workflows/installer-check.yaml
- idf-rust.Containerfile
- install-rust-toolchain.sh
Fixed environment variables as they were not working for `esp32c3`. I've run [this CI](https://github.com/esp-rs/rust-build/pull/110) [on my fork](https://github.com/SergioGasquez/rust-build/actions/runs/2678460138) and all the targets seem to be working in esp-idf release v4.4 and for bare-metal (esp-idf master is failing for all of them as expected due to https://github.com/esp-rs/esp-idf-sys/issues/99). I've also updated Containerfile default values
> Exports were not properly working for `esp32c3`

- README.md
- install-rust-toolchain.sh
Just noticed this one. While using only the `i` extension will likely be fine for simple demos, it's best to include all supported extensions. Hardware-accelerated multiplication/division (`m`) and compressed instructions (`c`) are both pretty useful.
> Fix the RISC-V target in the README

- install-rust-toolchain.sh
This improves a few things about the install script:
- Set strict mode and check that there are no unset variables and fix instances of where that is currently the case
- Use bash builtin conditional characters
- Restructure the export file logic and only make it output to shell if `EXPORT_FILE` is unset
Fixes #113.
> Modernize bash script

- .github/workflows/publish-idf-rust-tags.yml
- build-template-project.sh
Add some logic to compile template projects before publishing the tags to espressif/idf-rust
> Build template projects before publishing tags to Dockerhub

- .github/workflows/build-rust-aarch64-apple-darwin-self-hosted-dispatch.yaml
The `openssl-sys` crate will either link against a Homebrew-provided
OpenSSL, or it will build OpenSSL itself.
Using the `cargo-native-static` build option will force `openssl-sys` to
build OpenSSL itself. This produces binaries that do not link against
any non-system-provided libraries. This is how official builds of
`rust-lang/rust` are performed. See
https://github.com/rust-lang/rust/blob/da5b546d2e563747b16a16dae83bacf49aa0bf3b/src/ci/run.sh#L54
Fixes: #29
> Build without linking to homebrew libs

- .github/workflows/installer-check.yaml
- README.md
- install-rust-toolchain.sh
Improve the CI that test the installer:
- Add a test that verifies the 3 installation modes
- Add a test that uses the installer with different arguments
- Update `crate-check` job to contain more test cases
- Update documentation with `1.62.1.0` argument changes
- Test cases are now split:
- On PRs and pushes only tests that check that projects are building will be executed
- When triggering the workflow manually, all the test cases will be executed
> Add more test cases

- README.md
To source scripts in PowerShell you must use the `.` operator. Unlike bash, `source` is not supported.
> Change PowerShell `source` references to `.`

- install-rust-toolchain.sh
`install_system_packages` function was duplicated https://github.com/esp-rs/rust-build/blob/main/install-rust-toolchain.sh#L414-L444
> Remove duplicated `install_system_packages` function

- install-rust-toolchain.sh
At the moment, `sscache` is not generating artifacts for `x86_64-unknown-linux-gnu` target.  Opened https://github.com/mozilla/sccache/pull/1330 to add it.
Closes #141
> sccache support

- install-rust-toolchain.sh
I was trying to install the rust compiler with Xtensa support as well as the toolchain
under a different folder than my main rust folder (at ~/.cargo) and ran into some issues and needed this fix for it to work. 
Maybe it would be interesting for you to have it upstream as well?
Thank you for this project!
> Fix for toolchain installation folder

- support/rust-build/aarch64-unknown-linux-gnu/build.sh
- support/rust-build/x86_64-pc-windows-gnu/build-rust-toolchain-msys2.sh
- support/rust-build/x86_64-unknown-linux-gnu/build.sh
The proc-macro server needs to be built and distributed for rust-analyzer to be able to expand proc-macros.
Fixes esp-rs/espup#254.
> Build rust-analyzer-proc-macro-srv

- README.md
This one-line addition to documentation clarifies an admittedly simple step that was not specified in the installation documentation.
> docs: Update readme to include 'espup install'

- .github/workflows/build-aarch64-apple-darwin.yaml
- .github/workflows/build-aarch64-unknown-linux-gnu.yaml
- .github/workflows/build-rust-src.yaml
- .github/workflows/build-x86_64-apple-darwin.yaml
- .github/workflows/build-x86_64-pc-windows-gnu.yaml
- .github/workflows/build-x86_64-pc-windows-msvc.yaml
- .github/workflows/build-x86_64-unknown-linux-gnu.yaml
It was generating a deprecation warning. More info: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Avoid using set-output

- .github/workflows/build-aarch64-apple-darwin.yaml
- .github/workflows/build-aarch64-unknown-linux-gnu.yaml
- .github/workflows/build-rust-artifacts.yaml
- .github/workflows/build-rust-src.yaml
- .github/workflows/build-x86_64-apple-darwin.yaml
- .github/workflows/build-x86_64-pc-windows-gnu.yaml
- .github/workflows/build-x86_64-pc-windows-msvc.yaml
- .github/workflows/build-x86_64-unknown-linux-gnu.yaml
- .github/workflows/prepare-release.yaml
- .github/workflows/publish-idf-rust-tags.yml
- .github/workflows/upload-installer.yaml
- README.md
- install-rust-toolchain.sh
- support/rust-build/Repackage-RustRelease.ps1
- support/rust-build/x86_64-pc-windows-gnu/Prepare-BuildEnvironment.ps1
- support/rust-build/x86_64-pc-windows-msvc/Prepare-BuildEnvironment.ps1
Release 1.74.0.0
Changes:
- macOS x86 build by GitHub
- Windows new self hosted runners - updated boostrap scripts for MSVC
- Linux aarch64 update builder
> Release 1.74.0.0
